# Generated by Django 5.1.4 on 2026-05-26 18:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('factor_value', models.DecimalField(decimal_places=6, max_digits=15)),
                ('unit', models.CharField(max_length=30)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'emission_factor',
                'ordering': ['category', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='EmissionCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('co2e_kg', models.DecimalField(decimal_places=4, max_digits=15)),
                ('calculation_notes', models.TextField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('activity_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='records.activityrecord')),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculations_made', to=settings.AUTH_USER_MODEL)),
                ('emission_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='emissions.emissionfactor')),
            ],
            options={
                'db_table': 'emission_calculation',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
