# Generated by Django 5.1.4 on 2026-05-26 18:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_date', models.DateField()),
                ('category', models.CharField(choices=[('fuel_diesel', 'Fuel - Diesel'), ('fuel_petrol', 'Fuel - Petrol'), ('fuel_lpg', 'Fuel - LPG'), ('electricity_grid', 'Electricity (Grid)'), ('flight_short_haul', 'Flight - Short Haul'), ('flight_long_haul', 'Flight - Long Haul'), ('hotel_stay', 'Hotel Stay'), ('ground_transport_car', 'Ground Transport - Car'), ('ground_transport_rail', 'Ground Transport - Rail')], max_length=30)),
                ('subcategory', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit', models.CharField(max_length=30)),
                ('normalized_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('normalized_unit', models.CharField(max_length=30)),
                ('scope', models.CharField(choices=[('1', 'Scope 1'), ('2', 'Scope 2'), ('3', 'Scope 3')], max_length=1)),
                ('state', models.CharField(choices=[('ingested', 'Ingested'), ('needs_review', 'Needs Review'), ('approved', 'Approved'), ('locked', 'Locked')], default='ingested', max_length=15)),
                ('quality_tier', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=10)),
                ('quality_notes', models.JSONField(default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_records', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='core.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('source_row', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_record', to='ingestion.sourcerow')),
            ],
            options={
                'db_table': 'activity_record',
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True)),
                ('activity_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='records.activityrecord')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'record_revision',
                'ordering': ['-changed_at'],
            },
        ),
    ]
