# Generated by Django 5.1.4 on 2026-05-26 18:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Procurement'), ('utility', 'Utility CSV'), ('travel', 'Corporate Travel')], max_length=20)),
                ('filename', models.CharField(max_length=500)),
                ('file_hash', models.CharField(max_length=64)),
                ('storage_path', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('error_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='core.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'source_file',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'file_hash')},
            },
        ),
        migrations.CreateModel(
            name='SourceRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.IntegerField()),
                ('raw_payload', models.JSONField()),
                ('parse_status', models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed')], default='ok', max_length=10)),
                ('parse_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ingestion.sourcefile')),
            ],
            options={
                'db_table': 'source_row',
                'ordering': ['source_file', 'row_index'],
                'unique_together': {('source_file', 'row_index')},
            },
        ),
    ]
